server:
  port: 8443
  ssl:
     enabled: true
     key-store: classpath:keystore.p12
     key-store-type: PKCS12
     key-store-password: Nitkkr@109689
#    enabled: true
#    key-alias: diary
#    key-store: classpath:keystore.p12
#    key-store-type: JKS
#    key-store-password: Nitkkr@109689
#    http: 8080